@startuml
!theme materia
skinparam componentStyle uml1
skinparam backgroundColor MOTIVATION
skinparam linetype ortho
skinparam actorStyle awesome
skinparam defaultTextAlignment center
skinparam classarrowcolor Black
skinparam SequenceMessageAlign reverseDirection

title [ARCH]: Recommendation system

actor Клиент as Client
component FastAPI
node RSEngine <<Рекомендательная система>> {
    rectangle EventGetter <<Выгружает события>>
    rectangle Preparer <<Подготавливает данные \n для модели>>
    rectangle Loader <<Загружает наборы \n рекомендованных фильмов в DB>>
    rectangle CollaborativeFiltering <<Делает \n рекомендовации фильмов>>
    rectangle PopularFilms
}
cloud Nginx
database ClickHouse <<Хранение событий пользователей>>
database Cache <<Кэш запросов>>
database DB <<Хранение рекомендаций на неделю>>

Client -->Nginx: Запрос списка  \n рекомендованных фильмов
Nginx ---> FastAPI: Проксирование запроса
FastAPI <-up--> DB: Запрос рекомендаций
ClickHouse --> EventGetter
Preparer -> CollaborativeFiltering
EventGetter -right-> Preparer
EventGetter -down-> PopularFilms
PopularFilms --> DB

CollaborativeFiltering -down-> Loader
Loader -down--> DB: Сохранение рекомендаций для \n пользователей
FastAPI <-up--> Cache: Кэширование данных
@enduml
